on:
  push:
    branches:
      - master

name: Deployment Workflow
env:
  IMAGE_TAG: ${{ github.run_number }}
  AUTHOR: '`${{ github.actor }}`'
  APP: '`upet-frontend-test`'
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'nocd')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Installing modules
        run: yarn install

      - name: Build
        run: yarn build

      - name: Export Yarn
        run: yarn export

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
